# 命令头 0x020B
# 长度 40

# 己方英雄X坐标 (float, m)
float32 hero_x
# 己方英雄Y坐标 (float, m)
float32 hero_y
# 己方工程X坐标 (float, m)
float32 engineer_x
# 己方工程Y坐标 (float, m)
float32 engineer_y
# 己方3号步兵X坐标 (float, m)
float32 infantry3_x
# 己方3号步兵Y坐标 (float, m)
float32 infantry3_y
# 己方4号步兵X坐标 (float, m)
float32 infantry4_x
# 己方4号步兵Y坐标 (float, m)
float32 infantry4_y
# 己方5号步兵X坐标 (float, m)
float32 infantry5_x
# 己方5号步兵Y坐标 (float, m)
float32 infantry5_y
