# 命令头 0x0305
# 长度 24

# 英雄X坐标 (uint16_t, cm)
uint16 hero_x
# 英雄Y坐标 (uint16_t, cm)
uint16 hero_y
# 工程X坐标 (uint16_t, cm)
uint16 engineer_x
# 工程Y坐标 (uint16_t, cm)
uint16 engineer_y
# 3号步兵X坐标 (uint16_t, cm)
uint16 infantry3_x
# 3号步兵Y坐标 (uint16_t, cm)
uint16 infantry3_y
# 4号步兵X坐标 (uint16_t, cm)
uint16 infantry4_x
# 4号步兵Y坐标 (uint16_t, cm)
uint16 infantry4_y
# 5号步兵X坐标 (uint16_t, cm)
uint16 infantry5_x
# 5号步兵Y坐标 (uint16_t, cm)
uint16 infantry5_y
# 哨兵X坐标 (uint16_t, cm)
uint16 sentry_x
# 哨兵Y坐标 (uint16_t, cm)
uint16 sentry_y
