# 命令头 0x0304
# 长度 12

# 鼠标X速
int16 mouse_vx
# 鼠标Y速
int16 mouse_vy
# 滚轮速
int16 wheel_speed
# 左键(1:按)
uint8 left_button
# 右键(1:按)
uint8 right_button
# 键盘按键 W
uint8 w
# 键盘按键 S
uint8 s
# 键盘按键 A
uint8 a
# 键盘按键 D
uint8 d
# 键盘按键 Shift
uint8 shift
# 键盘按键 Ctrl
uint8 ctrl
# 键盘按键 Q
uint8 q
# 键盘按键 E
uint8 e
# 键盘按键 R
uint8 r
# 键盘按键 F
uint8 f
# 键盘按键 G
uint8 g
# 键盘按键 Z
uint8 z
# 键盘按键 X
uint8 x
# 键盘按键 C
uint8 c
# 键盘按键 V
uint8 v
# 键盘按键 B
uint8 b
