# 命令头 0x0209
# 长度 4

# 基地增益点
uint8 base_gain
# 己方中央高地
uint8 own_center_highland
# 对方中央高地
uint8 enemy_center_highland
# 己方梯形高地
uint8 own_trapezoid_highland
# 对方梯形高地
uint8 enemy_trapezoid_highland
# 地形跨越(飞坡) 位映射
uint8 terrain_crossing_ramp
# 地形跨越(中央高地) 位映射
uint8 terrain_crossing_highland
# 地形跨越(公路区) 位映射
uint8 terrain_crossing_road
# 堡垒
uint8 fort
# 前哨站
uint8 outpost
# 补给区
uint8 supply_area
# 隧道、装配增益点等
uint16 other_locations
